const computerIcon = {
  v: '5.12.1',
  fr: 60,
  ip: 0,
  op: 90,
  w: 430,
  h: 430,
  nm: 'wired-outline-478-computer-display',
  ddd: 0,
  assets: [
    {
      id: 'comp_0',
      nm: 'in-reveal',
      fr: 60,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: 'display 2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [215, 345, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 130, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.32, y: 1 },
                        o: { x: 0.34, y: 0 },
                        t: 18,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [35, 160],
                              [35.25, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [35, 160],
                              [30, 100],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 2',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 1,
                  ty: 'sh',
                  ix: 2,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.32, y: 1 },
                        o: { x: 0.34, y: 0 },
                        t: 18,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-35, 160],
                              [-35, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-30, 100],
                              [-35, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 3',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 2,
                  ty: 'sh',
                  ix: 3,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.32, y: 1 },
                        o: { x: 0.34, y: 0 },
                        t: 18,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-70, 160],
                              [70, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-70, 160],
                              [70, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 4',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 6,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector',
              np: 4,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 18,
          op: 1800,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: 'display',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.32, y: 1 },
                  o: { x: 0.34, y: 0 },
                  t: 18,
                  s: [215, 354.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 90, s: [215, 294.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 79.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.058, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 30,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-0.096, 79.179],
                              [-0.25, 79.085],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [0.029, 70.179],
                              [-0.125, 70.085],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0], y: [1] },
                        o: { x: [0.167], y: [0.167] },
                        t: 1,
                        s: [2.5],
                      },
                      { t: 30, s: [10] },
                    ],
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [-0.152, 70.047], ix: 2 },
                  a: { a: 0, k: [-0.152, 70.047], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector 2',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-0.75, 59],
                              [-21.25, 79],
                              [-21.25, 80],
                              [-0.75, 100],
                              [0.75, 100],
                              [20.75, 80],
                              [20.75, 79],
                              [0.75, 59],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.058, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 30,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, 59],
                              [-170, 79],
                              [-170, 80],
                              [-150, 100],
                              [150, 100],
                              [170, 80],
                              [170, 79],
                              [150, 59],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 80],
                              [-150, 100],
                              [150, 100],
                              [170, 80],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 6,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector 3',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-0.25, 59],
                              [0.75, 59],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.833, y: 0.833 },
                        o: { x: 0.333, y: 0 },
                        t: 30,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-149.5, 59],
                              [150, 59],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.833, y: 0.833 },
                        o: { x: 0.167, y: 0.167 },
                        t: 36,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-164.5, 58.184],
                              [164.979, 58.184],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.058, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 39,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-169.5, 56.369],
                              [169.931, 56.369],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-170, 40],
                              [170, 40],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 5',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 6,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: {
                    a: 1,
                    k: [
                      { t: 0, s: [0], h: 1 },
                      { t: 30, s: [100], h: 1 },
                    ],
                    ix: 7,
                  },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 1,
          op: 1800,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: 'mask',
          parent: 2,
          td: 1,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [0, 0, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.047, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 30,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -0.018],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, -0.018],
                              [0, 0],
                            ],
                            v: [
                              [-150, 60],
                              [-170, 60.032],
                              [-170, 60.032],
                              [-170, 60.032],
                              [170, 60.032],
                              [170, 60.032],
                              [170, 60.032],
                              [150, 60],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 40],
                              [-170, 40],
                              [170, 40],
                              [170, 40],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: { a: 0, k: [1, 0, 0, 1], ix: 4 },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: 'Fill 1',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 1,
          op: 89,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 4,
          nm: 'Shape Layer 1',
          tt: 1,
          tp: 3,
          sr: 1,
          ks: {
            o: { a: 0, k: 50, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 36,
                  s: [3, 201, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 90, s: [158, 201, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.66, y: 0 },
                        t: 36,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 66.328,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [236, -178],
                              [110.5, -184],
                              [366, 83.5],
                              [499, 90],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 90,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 4,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 12,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.66, y: 0 },
                        t: 36,
                        s: [-418, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      { t: 90, s: [114, 0] },
                    ],
                    ix: 2,
                  },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: {
                    a: 1,
                    k: [
                      { t: 11.34, s: [0], h: 1 },
                      { t: 36, s: [100], h: 1 },
                      { t: 90, s: [0], h: 1 },
                    ],
                    ix: 7,
                  },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 7.5,
          op: 89,
          st: 7.5,
          ct: 1,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 3,
      nm: 'control',
      sr: 1,
      ks: {
        o: { a: 0, k: 0, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [0, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: 'stroke',
          np: 3,
          mn: 'Pseudo/@@jsXte4rTTdyYAphyvuNs/Q',
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 7,
              nm: 'Menu',
              mn: 'Pseudo/@@jsXte4rTTdyYAphyvuNs/Q-0001',
              ix: 1,
              v: { a: 0, k: 1, ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'primary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [1, 1, 1], ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'secondary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [0.188, 0.502, 0.91], ix: 1 },
            },
          ],
        },
      ],
      ip: 0,
      op: 221,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 0,
      nm: 'in-reveal',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [215, 215, 0], ix: 2, l: 2 },
        a: { a: 0, k: [215, 215, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 430,
      h: 430,
      ip: 0,
      op: 100,
      st: 0,
      bm: 0,
    },
  ],
  markers: [{ tm: 0, cm: 'default:in-reveal', dr: 90 }],
  props: {},
};

export default computerIcon;
