const shopIcon = {
  v: '5.8.1',
  fr: 60,
  ip: 0,
  op: 90,
  w: 430,
  h: 430,
  nm: '146-basket-trolley-shopping-card-outline',
  ddd: 0,
  assets: [
    {
      id: 'comp_0',
      nm: 'in-reveal',
      fr: 60,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: 'Shape Layer 2',
          parent: 2,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.167], y: [0.167] },
                  t: 21,
                  s: [7],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 43,
                  s: [-3],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 66,
                  s: [1],
                },
                { t: 90, s: [0] },
              ],
              ix: 10,
            },
            p: { a: 0, k: [-26.474, 18.188, 0], ix: 2, l: 2 },
            a: { a: 0, k: [-26.474, 18.188, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.833, y: 0.833 },
                        o: { x: 0.167, y: 0.167 },
                        t: 22,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0.541, -1.001],
                              [0.014, -0.094],
                              [0.895, -0.698],
                              [4.613, -0.526],
                              [0, 0],
                              [1.028, -1.275],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [-0.013, 0.024],
                              [-0.176, 0.51],
                              [-3.413, 2.663],
                              [-15.137, 1.724],
                              [0, 0],
                              [-1.61, 1.996],
                            ],
                            v: [
                              [-24.826, 10.96],
                              [34.265, 4.23],
                              [35.498, 4.079],
                              [34.898, 6.708],
                              [34.86, 6.779],
                              [33.007, 8.433],
                              [21.785, 11.952],
                              [-23.625, 17.125],
                              [-26.944, 18.694],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.07, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 27,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0.014, -0.094],
                              [3.059, -2.551],
                              [4.613, -0.526],
                              [0, 0],
                              [1.028, -1.275],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [-1.469, 4.319],
                              [-3.325, 2.773],
                              [-15.137, 1.724],
                              [0, 0],
                              [-1.61, 1.996],
                            ],
                            v: [
                              [-26.573, -0.81],
                              [38.628, -5.243],
                              [39.878, -5.243],
                              [39.391, -3.561],
                              [39.435, -2.768],
                              [33.733, 7.943],
                              [21.785, 11.952],
                              [-23.625, 17.125],
                              [-26.944, 18.694],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 66,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [2.276, -7.85],
                              [3.059, -2.551],
                              [4.613, -0.526],
                              [0, 0],
                              [1.028, -1.275],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [-1.27, 4.381],
                              [-3.325, 2.773],
                              [-15.137, 1.724],
                              [0, 0],
                              [-1.61, 1.996],
                            ],
                            v: [
                              [-30.939, -28.027],
                              [45.5, -28],
                              [46.75, -28],
                              [46.263, -26.319],
                              [39.435, -2.768],
                              [33.733, 7.943],
                              [21.785, 11.952],
                              [-23.625, 17.125],
                              [-26.944, 18.694],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'tm',
                  s: {
                    a: 1,
                    k: [
                      { t: 18, s: [100], h: 1 },
                      { t: 22, s: [0], h: 1 },
                    ],
                    ix: 1,
                  },
                  e: { a: 0, k: 100, ix: 2 },
                  o: { a: 0, k: 0, ix: 3 },
                  m: 1,
                  ix: 2,
                  nm: 'Trim Paths 1',
                  mn: 'ADBE Vector Filter - Trim',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('146-basket-trolley-shopping-card-outline').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 1.75,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('146-basket-trolley-shopping-card-outline').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 3',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [-2.131, 0],
                        [-1.222, -7.251],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [3.378, 0],
                        [2.52, 14.961],
                        [0, 0],
                      ],
                      v: [
                        [-47, -38],
                        [-40.608, -38],
                        [-31.549, -27.884],
                        [-24, 17],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: 'Path 3',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'tm',
                  s: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.518], y: [0.163] },
                        o: { x: [0.401], y: [0.186] },
                        t: 21,
                        s: [100],
                      },
                      {
                        i: { x: [0.291], y: [1] },
                        o: { x: [0.086], y: [0.362] },
                        t: 25,
                        s: [80.846],
                      },
                      { t: 66, s: [0] },
                    ],
                    ix: 1,
                  },
                  e: { a: 0, k: 100, ix: 2 },
                  o: { a: 0, k: 0, ix: 3 },
                  m: 1,
                  ix: 2,
                  nm: 'Trim Paths 1',
                  mn: 'ADBE Vector Filter - Trim',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('146-basket-trolley-shopping-card-outline').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 1.75,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('146-basket-trolley-shopping-card-outline').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 2',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 1,
          op: 301,
          st: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: 'Shape Layer 1',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.31, y: 1 },
                  o: { x: 0.167, y: 0.167 },
                  t: 1,
                  s: [214.333, 373.831, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 31, s: [214.333, 318.831, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [2.32, 28.062, 0], ix: 1, l: 2 },
            s: { a: 0, k: [370, 370, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.31, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 1,
                        s: [
                          {
                            i: [
                              [-0.11, 0],
                              [0, -0.11],
                              [0.11, 0],
                              [0, 0.11],
                            ],
                            o: [
                              [0.11, 0],
                              [0, 0.11],
                              [-0.11, 0],
                              [0, -0.11],
                            ],
                            v: [
                              [-0.197, -7.71],
                              [0.003, -7.511],
                              [-0.197, -7.311],
                              [-0.397, -7.511],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 31,
                        s: [
                          {
                            i: [
                              [-4.142, 0],
                              [0, -4.142],
                              [4.142, 0],
                              [0, 4.142],
                            ],
                            o: [
                              [4.142, 0],
                              [0, 4.142],
                              [-4.142, 0],
                              [0, -4.142],
                            ],
                            v: [
                              [0, -7.5],
                              [7.5, 0],
                              [0, 7.5],
                              [-7.5, 0],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.4, 0.631, 0.933, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('146-basket-trolley-shopping-card-outline').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 1.75,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('146-basket-trolley-shopping-card-outline').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 1,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [25, 31.5], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Ellipse 2',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.31, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 1,
                        s: [
                          {
                            i: [
                              [-0.216, 0],
                              [0, -0.216],
                              [0.216, 0],
                              [0, 0.216],
                            ],
                            o: [
                              [0.216, 0],
                              [0, 0.216],
                              [-0.216, 0],
                              [0, -0.216],
                            ],
                            v: [
                              [-0.068, -7.824],
                              [0.324, -7.432],
                              [-0.068, -7.041],
                              [-0.459, -7.432],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 31,
                        s: [
                          {
                            i: [
                              [-4.142, 0],
                              [0, -4.142],
                              [4.142, 0],
                              [0, 4.142],
                            ],
                            o: [
                              [4.142, 0],
                              [0, 4.142],
                              [-4.142, 0],
                              [0, -4.142],
                            ],
                            v: [
                              [0, -7.5],
                              [7.5, 0],
                              [0, 7.5],
                              [-7.5, 0],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.4, 0.631, 0.933, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('146-basket-trolley-shopping-card-outline').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 1.75,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('146-basket-trolley-shopping-card-outline').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 1,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [-19.375, 31.5], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Ellipse 1',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [1.028, -1.275],
                        [-5.645, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [-1.61, 1.996],
                        [9.25, 0],
                        [0, 0],
                      ],
                      v: [
                        [-23.625, 17.125],
                        [-26.944, 18.694],
                        [-22.875, 24],
                        [24.5, 24],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'rd',
                  nm: 'Round Corners 1',
                  r: { a: 0, k: 10, ix: 1 },
                  ix: 2,
                  mn: 'ADBE Vector Filter - RC',
                  hd: false,
                },
                {
                  ty: 'tm',
                  s: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.833], y: [0.833] },
                        o: { x: [0.167], y: [0.167] },
                        t: 1,
                        s: [100],
                      },
                      { t: 22, s: [0] },
                    ],
                    ix: 1,
                  },
                  e: { a: 0, k: 100, ix: 2 },
                  o: { a: 0, k: 0, ix: 3 },
                  m: 1,
                  ix: 3,
                  nm: 'Trim Paths 1',
                  mn: 'ADBE Vector Filter - Trim',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('146-basket-trolley-shopping-card-outline').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 1.75,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('146-basket-trolley-shopping-card-outline').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 1',
              np: 4,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 1,
          op: 301,
          st: 1,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 3,
      nm: 'control',
      sr: 1,
      ks: {
        o: { a: 0, k: 0, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [0, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: 'stroke',
          np: 3,
          mn: 'Pseudo/@@gAocx74SRf2RbxByLA5JYA',
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 7,
              nm: 'Menu',
              mn: 'Pseudo/@@gAocx74SRf2RbxByLA5JYA-0001',
              ix: 1,
              v: { a: 0, k: 1, ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'primary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [1, 1, 1], ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'secondary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [0.4, 0.631, 0.933], ix: 1 },
            },
          ],
        },
      ],
      ip: 0,
      op: 164,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 0,
      nm: 'in-reveal',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [215, 215, 0], ix: 2, l: 2 },
        a: { a: 0, k: [215, 215, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 430,
      h: 430,
      ip: 0,
      op: 100,
      st: 0,
      bm: 0,
    },
  ],
  markers: [{ tm: 0, cm: 'default:in-reveal', dr: 90 }],
};

export default shopIcon;
