const computer = {
  v: '5.12.1',
  fr: 60,
  ip: 0,
  op: 120,
  w: 430,
  h: 430,
  nm: 'wired-outline-478-computer-display',
  ddd: 0,
  assets: [
    {
      id: 'comp_1',
      nm: 'hover-angle',
      fr: 60,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: 'display',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [215, 215, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [0.029, 70.179],
                        [-0.125, 70.085],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 10,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 0 },
                        o: { x: 0.333, y: 0.333 },
                        t: 0,
                        s: [0, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      {
                        i: { x: 0.4, y: 0.4 },
                        o: { x: 0.6, y: 0.6 },
                        t: 60,
                        s: [0, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      { t: 120, s: [0, 0] },
                    ],
                    ix: 2,
                  },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0, 0.4], y: [1, 1] },
                        o: { x: [0.333, 0.333], y: [0, 0] },
                        t: 0,
                        s: [100, 100],
                      },
                      {
                        i: { x: [0.4, 0.4], y: [1, 1] },
                        o: { x: [0.6, 0.6], y: [0, 0] },
                        t: 60,
                        s: [80, 100],
                      },
                      { t: 120, s: [100, 100] },
                    ],
                    ix: 3,
                  },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector 2',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 80],
                              [-150, 100],
                              [150, 100],
                              [170, 80],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-7.927, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [7.927, 0],
                            ],
                            o: [
                              [-7.927, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [7.927, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-107.647, -160],
                              [-122, -140],
                              [-122, 80],
                              [-107.647, 100],
                              [107.647, 100],
                              [122, 80],
                              [122, -140],
                              [107.647, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 11.046],
                              [0, 0],
                              [11.046, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 80],
                              [-150, 100],
                              [150, 100],
                              [170, 80],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 1,
                  ty: 'sh',
                  ix: 2,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [35, 160],
                              [30, 100],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [1, 160],
                              [1, 100],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [35, 160],
                              [30, 100],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 2',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 2,
                  ty: 'sh',
                  ix: 3,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-30, 100],
                              [-35, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-39, 100],
                              [-44, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-30, 100],
                              [-35, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 3',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 3,
                  ty: 'sh',
                  ix: 4,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-70, 160],
                              [70, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-61, 160],
                              [79, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-70, 160],
                              [70, 160],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 4',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ind: 4,
                  ty: 'sh',
                  ix: 5,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-170, 40],
                              [170, 40],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-122, 40],
                              [122, 40],
                            ],
                            c: false,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [-170, 40],
                              [170, 40],
                            ],
                            c: false,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 5',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [1, 1, 1, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('primary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 6,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.primary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'primary',
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector',
              np: 6,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 0,
          op: 1800,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: 'mask',
          td: 1,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [215, 215, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 0,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 40],
                              [-170, 40],
                              [170, 40],
                              [170, 40],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.4, y: 1 },
                        o: { x: 0.6, y: 0 },
                        t: 60,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [7.927, 0],
                            ],
                            o: [
                              [-7.927, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-107.647, -160],
                              [-122, -140],
                              [-122, 40],
                              [-122, 40],
                              [122, 40],
                              [122, 40],
                              [122, -140],
                              [107.647, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [11.046, 0],
                            ],
                            o: [
                              [-11.046, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, -11.046],
                              [0, 0],
                            ],
                            v: [
                              [-150, -160],
                              [-170, -140],
                              [-170, 40],
                              [-170, 40],
                              [170, 40],
                              [170, 40],
                              [170, -140],
                              [150, -160],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: { a: 0, k: [1, 0, 0, 1], ix: 4 },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: 'Fill 1',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Vector',
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 1,
          op: 116,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: 'Shape Layer 1',
          tt: 1,
          tp: 2,
          sr: 1,
          ks: {
            o: { a: 0, k: 50, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 5.615,
                  s: [162, 201, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 63.131,
                  s: [54, 201, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 120, s: [158, 201, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 20.781,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 53.63671875,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 4,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 12,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 20.781,
                        s: [42, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      { t: 53.63671875, s: [-418, 0] },
                    ],
                    ix: 2,
                  },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: {
                    a: 1,
                    k: [
                      { t: 5.615, s: [0], h: 1 },
                      { t: 20.781, s: [100], h: 1 },
                      { t: 53.63671875, s: [0], h: 1 },
                    ],
                    ix: 7,
                  },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 2',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.167, y: 0.167 },
                        t: 10.67,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.833, y: 0.833 },
                        o: { x: 0.333, y: 0 },
                        t: 27.1,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [110.5, -184],
                              [366, 83.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 41,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 4,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 12,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.833, y: 0.833 },
                        o: { x: 0.167, y: 0.167 },
                        t: 10.67,
                        s: [42, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      { t: 41, s: [-418, 0] },
                    ],
                    ix: 2,
                  },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: {
                    a: 1,
                    k: [
                      { t: -4.494, s: [0], h: 1 },
                      { t: 10.67, s: [100], h: 1 },
                      { t: 41, s: [0], h: 1 },
                    ],
                    ix: 7,
                  },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 3',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.66, y: 0 },
                        t: 60.605,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.333, y: 0 },
                        t: 90.934,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [236, -178],
                              [110.5, -184],
                              [366, 83.5],
                              [499, 90],
                            ],
                            c: true,
                          },
                        ],
                      },
                      {
                        t: 120,
                        s: [
                          {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [156, -177],
                              [138.5, -177],
                              [394, 90.5],
                              [419, 91],
                            ],
                            c: true,
                          },
                        ],
                      },
                    ],
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 4,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.188, 0.502, 0.91, 1],
                    ix: 3,
                    x: "var $bm_rt;\n$bm_rt = comp('wired-outline-478-computer-display').layer('control').effect('secondary')('Color');",
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: {
                    a: 0,
                    k: 12,
                    ix: 5,
                    x: "var $bm_rt;\n$bm_rt = $bm_mul($bm_div(value, 1), comp('wired-outline-478-computer-display').layer('control').effect('stroke')('Menu'));",
                  },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: '.secondary',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                  cl: 'secondary',
                },
                {
                  ty: 'tr',
                  p: {
                    a: 1,
                    k: [
                      {
                        i: { x: 0.667, y: 1 },
                        o: { x: 0.66, y: 0 },
                        t: 60.605,
                        s: [-418, 0],
                        to: [0, 0],
                        ti: [0, 0],
                      },
                      { t: 120, s: [114, 0] },
                    ],
                    ix: 2,
                  },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: {
                    a: 1,
                    k: [
                      { t: 35.945, s: [0], h: 1 },
                      { t: 60.605, s: [100], h: 1 },
                      { t: 120, s: [0], h: 1 },
                    ],
                    ix: 7,
                  },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'Shape 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 7.5,
          op: 116,
          st: 7.5,
          ct: 1,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 3,
      nm: 'control',
      sr: 1,
      ks: {
        o: { a: 0, k: 0, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [0, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: 'stroke',
          np: 3,
          mn: 'Pseudo/@@jsXte4rTTdyYAphyvuNs/Q',
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 7,
              nm: 'Menu',
              mn: 'Pseudo/@@jsXte4rTTdyYAphyvuNs/Q-0001',
              ix: 1,
              v: { a: 0, k: 1, ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'primary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [1, 1, 1], ix: 1 },
            },
          ],
        },
        {
          ty: 5,
          nm: 'secondary',
          np: 3,
          mn: 'ADBE Color Control',
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 2,
              nm: 'Color',
              mn: 'ADBE Color Control-0001',
              ix: 1,
              v: { a: 0, k: [0.188, 0.502, 0.91], ix: 1 },
            },
          ],
        },
      ],
      ip: 0,
      op: 221,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 0,
      nm: 'hover-angle',
      refId: 'comp_1',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [215, 215, 0], ix: 2, l: 2 },
        a: { a: 0, k: [215, 215, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 430,
      h: 430,
      ip: 0,
      op: 130,
      st: 0,
      bm: 0,
    },
  ],
  markers: [{ tm: 0, cm: 'default:hover-angle', dr: 120 }],
  props: {},
};

export default computer;
