export type Rating = 1 | 2 | 3 | 4;

export interface Skill {
  id: number;
  name: string;
  icon: string;
  xp: Rating;
  mastery: Rating;
  affinity: Rating;
}

export const skills: Skill[] = [
  {
    id: 0,
    name: 'HTML 5',
    icon: '/icons/html.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    id: 1,
    name: 'CSS 3',
    icon: '/icons/css.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    id: 2,
    name: 'JavaScript',
    icon: '/icons/js.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    id: 3,
    name: 'Python',
    icon: '/icons/python.png',
    xp: 1,
    mastery: 2,
    affinity: 2,
  },
  {
    id: 4,
    name: 'Git',
    icon: '/icons/git.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 5,
    name: 'PHP',
    icon: '/icons/php.png',
    xp: 2,
    mastery: 2,
    affinity: 1,
  },
  {
    id: 6,
    name: 'SQL',
    icon: '/icons/sql.png',
    xp: 2,
    mastery: 2,
    affinity: 1,
  },
  {
    id: 7,
    name: 'NoSQL',
    icon: '/icons/nosql.png',
    xp: 3,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 8,
    name: 'Algorithmie',
    icon: '/icons/algo.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 9,
    name: 'React.js',
    icon: '/icons/react.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    name: 'Redux',
    icon: '/icons/redux.png',
    xp: 3,
    mastery: 3,
    affinity: 4,
    id: 10,
  },
  {
    id: 11,
    name: 'Next.js',
    icon: '/icons/next.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 12,
    name: 'Express.js',
    icon: '/icons/express.svg',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 13,
    name: 'Symfony',
    icon: '/icons/symfony.png',
    xp: 3,
    mastery: 3,
    affinity: 2,
  },
  {
    id: 14,
    name: 'Bootstrap',
    icon: '/icons/bootstrap.png',
    xp: 4,
    mastery: 4,
    affinity: 3,
  },
  {
    id: 15,
    name: 'Tailwind',
    icon: '/icons/tailwind.png',
    xp: 2,
    mastery: 3,
    affinity: 2,
  },
  {
    id: 16,
    name: 'GraphQL',
    icon: '/icons/graphql.png',
    xp: 1,
    mastery: 1,
    affinity: 1,
  },
  {
    id: 17,
    name: 'Apollo',
    icon: '/icons/apollo.png',
    xp: 1,
    mastery: 1,
    affinity: 1,
  },
  {
    id: 18,
    name: 'NodeJs',
    icon: '/icons/nodejs.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 19,
    name: 'TypeScript',
    icon: '/icons/typescript.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 20,
    name: 'JSX',
    icon: '/icons/jsx.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    id: 21,
    name: 'Twig',
    icon: '/icons/twig.png',
    xp: 3,
    mastery: 4,
    affinity: 2,
  },
  {
    id: 22,
    name: 'C',
    icon: '/icons/c.png',
    xp: 4,
    mastery: 3,
    affinity: 1,
  },
  {
    id: 23,
    name: 'Java',
    icon: '/icons/java.png',
    xp: 2,
    mastery: 2,
    affinity: 1,
  },
  {
    id: 24,
    name: 'Prestashop',
    icon: '/icons/prestashop.png',
    xp: 1,
    mastery: 2,
    affinity: 2,
  },
  {
    id: 25,
    name: 'Scrum',
    icon: '/icons/scrum.png',
    xp: 3,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 26,
    name: 'Github',
    icon: '/icons/github.png',
    xp: 4,
    mastery: 3,
    affinity: 3,
  },
  {
    id: 27,
    name: 'NPM',
    icon: '/icons/npm.png',
    xp: 4,
    mastery: 3,
    affinity: 3,
  },
  {
    id: 28,
    name: 'YARN',
    icon: '/icons/yarn.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 29,
    name: 'Adobe XD',
    icon: '/icons/adobexd.png',
    xp: 3,
    mastery: 3,
    affinity: 2,
  },
  {
    id: 30,
    name: 'Webstorm',
    icon: '/icons/webstorm.png',
    xp: 3,
    mastery: 2,
    affinity: 4,
  },
  {
    id: 31,
    name: 'Firebase',
    icon: '/icons/firebase.png',
    xp: 3,
    mastery: 3,
    affinity: 3,
  },
  {
    id: 32,
    name: 'Material UI',
    icon: '/icons/materialui.png',
    xp: 2,
    mastery: 2,
    affinity: 1,
  },
  {
    id: 33,
    name: 'OCaml',
    icon: '/icons/ocaml.png',
    xp: 1,
    mastery: 1,
    affinity: 1,
  },
  {
    id: 34,
    name: 'Swing',
    icon: '/icons/swing.png',
    xp: 1,
    mastery: 1,
    affinity: 1,
  },
  {
    id: 35,
    name: 'Pug',
    icon: '/icons/pug.png',
    xp: 1,
    mastery: 3,
    affinity: 2,
  },
  {
    id: 36,
    name: 'Trello',
    icon: '/icons/trello.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 37,
    name: 'PHPMyAdmin',
    icon: '/icons/phpmyadmin.png',
    xp: 2,
    mastery: 2,
    affinity: 1,
  },
  {
    id: 38,
    name: 'Atom',
    icon: '/icons/atom.png',
    xp: 4,
    mastery: 4,
    affinity: 2,
  },
  {
    id: 39,
    name: 'Composer',
    icon: '/icons/composer.png',
    xp: 3,
    mastery: 3,
    affinity: 2,
  },
  {
    id: 40,
    name: 'WAMP',
    icon: '/icons/wamp.png',
    xp: 3,
    mastery: 2,
    affinity: 2,
  },
  {
    id: 41,
    name: 'VSCode',
    icon: '/icons/vscode.png',
    xp: 4,
    mastery: 4,
    affinity: 4,
  },
  {
    id: 42,
    name: 'LAMP',
    icon: '/icons/lamp.png',
    xp: 1,
    mastery: 1,
    affinity: 2,
  },
  {
    id: 43,
    name: 'Bash',
    icon: '/icons/bash.png',
    xp: 4,
    mastery: 3,
    affinity: 4,
  },
  {
    id: 44,
    name: 'Netbeans',
    icon: '/icons/netbeans.png',
    xp: 1,
    mastery: 1,
    affinity: 1,
  },
  {
    id: 45,
    name: 'IntelliJ Idea',
    icon: '/icons/intellijidea.png',
    xp: 2,
    mastery: 1,
    affinity: 3,
  },
];

export default skills;
